import type { LessonDefinition, TopicDefinition, TopicId } from "./model"

export const topics: Record<TopicId, TopicDefinition> = {
  "arithmetic-equations": {
    id: "arithmetic-equations",
    title: "Fehlende Zahlen durch Rückwärtsrechnen finden",
    shortTitle: "Rechenketten",
    description: "Multiplikation und Division in der umgekehrten Reihenfolge auflösen.",
    prerequisites: [],
    courseOrder: 1,
  },
  "efficient-arithmetic": {
    id: "efficient-arithmetic",
    title: "Rechenvorteile erkennen und nutzen",
    shortTitle: "Geschickt rechnen",
    description: "Gemeinsame Faktoren, runde Summen und Differenzen vor dem Ausrechnen erkennen.",
    prerequisites: [],
    courseOrder: 2,
  },
  "mass-units": {
    id: "mass-units",
    title: "Kilogramm und Gramm sicher umrechnen",
    shortTitle: "kg und g",
    description: "Massen zwischen Kilogramm und Gramm umwandeln.",
    prerequisites: [],
    courseOrder: 3,
  },
  "fraction-of-quantity": {
    id: "fraction-of-quantity",
    title: "Den Bruchteil einer Menge bestimmen",
    shortTitle: "Bruchteil einer Menge",
    description: "Einen Bruch wie 3/4 von einer gegebenen Menge berechnen.",
    prerequisites: [],
    courseOrder: 4,
  },
  "time-fractions": {
    id: "time-fractions",
    title: "Bruchteile von Zeitspannen berechnen",
    shortTitle: "Zeit und Brüche",
    description: "Stunden und Minuten vereinheitlichen und Bruchteile davon bestimmen.",
    prerequisites: ["fraction-of-quantity"],
    courseOrder: 5,
  },
  "speed-distance-time": {
    id: "speed-distance-time",
    title: "Strecke, Zeit und Geschwindigkeit verbinden",
    shortTitle: "Bewegungsaufgaben",
    description: "Durchschnittsgeschwindigkeit und Aufholwege aus mehreren Zeitabschnitten berechnen.",
    prerequisites: ["time-fractions"],
    courseOrder: 6,
  },
  "data-tables": {
    id: "data-tables",
    title: "Daten aus Tabellen sicher verbinden",
    shortTitle: "Tabellen lesen",
    description: "Zeilen und Spalten gezielt lesen, fehlende Werte berechnen und Mittelwerte zurückverfolgen.",
    prerequisites: ["arithmetic-equations"],
    courseOrder: 7,
  },
  "money-calculations": {
    id: "money-calculations",
    title: "Preise, Anzahlen und Einnahmen verbinden",
    shortTitle: "Geld rechnen",
    description: "Gruppenpreise und Stückzahlen aus Preisen und Einnahmen berechnen.",
    prerequisites: [],
    courseOrder: 8,
  },
  "proportional-revenue": {
    id: "proportional-revenue",
    title: "Verhältnisse in Einnahmetabellen lösen",
    shortTitle: "Einnahmen und Verhältnis",
    description: "Bekannte Einnahmen abziehen und Gruppen in einem festen Verhältnis bündeln.",
    prerequisites: ["arithmetic-equations", "money-calculations"],
    courseOrder: 9,
  },
  "integer-combinations": {
    id: "integer-combinations",
    title: "Alle ganzzahligen Möglichkeiten systematisch finden",
    shortTitle: "Alle Möglichkeiten",
    description: "Kombinationen ohne Lücken und ohne Doppelzählungen aufzählen.",
    prerequisites: ["arithmetic-equations"],
    courseOrder: 10,
  },
  "number-constraints": {
    id: "number-constraints",
    title: "Zahlen unter mehreren Bedingungen vollständig finden",
    shortTitle: "Zahlen filtern",
    description: "Ziffern, Teilbarkeit und Stellenbedingungen zu einer vollständigen Lösungsmenge verbinden.",
    prerequisites: ["efficient-arithmetic"],
    courseOrder: 11,
  },
  "area-fractions": {
    id: "area-fractions",
    title: "Flächenanteile zählen und kürzen",
    shortTitle: "Flächenbrüche",
    description: "Verschieden grosse Platten in gleich grosse Flächeneinheiten übersetzen.",
    prerequisites: ["fraction-of-quantity"],
    courseOrder: 12,
  },
  "composite-areas": {
    id: "composite-areas",
    title: "Zusammengesetzte Flächen zerlegen",
    shortTitle: "Flächen zerlegen",
    description: "Rahmen, Ausschnitte und Kerben durch Ergänzen oder Subtrahieren berechnen.",
    prerequisites: ["arithmetic-equations"],
    courseOrder: 13,
  },
  "tiling-costs": {
    id: "tiling-costs",
    title: "Flächen mit minimalen Kosten belegen",
    shortTitle: "Platten optimieren",
    description: "Geometrische Passung und Kosten pro Fläche gemeinsam berücksichtigen.",
    prerequisites: ["area-fractions", "money-calculations"],
    courseOrder: 14,
  },
  "reverse-fractions": {
    id: "reverse-fractions",
    title: "Anteile rückwärts berechnen",
    shortTitle: "Anteile rückwärts",
    description: "Von einem bekannten Anteil auf die ursprüngliche Menge zurückgehen.",
    prerequisites: ["mass-units", "fraction-of-quantity"],
    courseOrder: 15,
  },
  "reverse-chains": {
    id: "reverse-chains",
    title: "Mehrschrittige Rückwärtsaufgaben",
    shortTitle: "Rückwärtsketten",
    description: "Mehrere Veränderungen in der richtigen umgekehrten Reihenfolge auflösen.",
    prerequisites: ["reverse-fractions"],
    courseOrder: 16,
  },
  "inverse-proportion": {
    id: "inverse-proportion",
    title: "Umgekehrt proportionale Grössen verstehen",
    shortTitle: "Umgekehrte Proportion",
    description: "Erkennen, wann weniger Personen eine Ressource entsprechend länger nutzen können.",
    prerequisites: ["arithmetic-equations", "fraction-of-quantity"],
    courseOrder: 17,
  },
  "changing-rates": {
    id: "changing-rates",
    title: "Verbrauch in mehreren Phasen berechnen",
    shortTitle: "Verbrauchsphasen",
    description: "Nach einer Veränderung zuerst den verbleibenden Vorrat und dann die neue Dauer bestimmen.",
    prerequisites: ["inverse-proportion"],
    courseOrder: 18,
  },
  "geometric-loci": {
    id: "geometric-loci",
    title: "Gebiete aus geometrischen Bedingungen konstruieren",
    shortTitle: "Geometrische Orte",
    description: "Abstände, Kreise und Mittelsenkrechten als Gebietsschranken lesen.",
    prerequisites: [],
    courseOrder: 19,
  },
  "coordinate-transformations": {
    id: "coordinate-transformations",
    title: "Punkte spiegeln, drehen und verschieben",
    shortTitle: "Koordinaten abbilden",
    description: "Koordinatenregeln für Spiegelungen, Vierteldrehungen und Verschiebungen anwenden.",
    prerequisites: ["arithmetic-equations"],
    courseOrder: 20,
  },
  "cube-nets": {
    id: "cube-nets",
    title: "Würfelnetze im Kopf falten",
    shortTitle: "Würfelnetze",
    description: "Aus einem Netz Nachbar- und Gegenflächen eines Würfels räumlich bestimmen.",
    prerequisites: [],
    courseOrder: 21,
  },
  "spatial-rolling": {
    id: "spatial-rolling",
    title: "Eine Pyramide im Kopf kippen",
    shortTitle: "Pyramide kippen",
    description: "Flächen beim Rollen über Kanten zuverlässig verfolgen.",
    prerequisites: [],
    courseOrder: 22,
  },
  "cuboid-surface": {
    id: "cuboid-surface",
    title: "Quadermasse aus Volumen erschliessen",
    shortTitle: "Quader und Oberfläche",
    description: "Bausteinmasse ableiten und alle sechs Flächen einer Oberfläche berechnen.",
    prerequisites: ["arithmetic-equations", "area-fractions"],
    courseOrder: 23,
  },
}

export const lessons: Record<TopicId, LessonDefinition> = {
  "arithmetic-equations": {
    id: "lesson-arithmetic-equations-v1",
    topicId: "arithmetic-equations",
    title: topics["arithmetic-equations"].title,
    goal: "Du kannst eine Rechenkette vom Ergebnis aus in umgekehrter Reihenfolge auflösen.",
    pages: [{
      eyebrow: "Rückwärtsdenken",
      title: "Mache jede Operation rückgängig",
      body: "Steht die gesuchte Zahl am Anfang einer Rechenkette, beginnst du beim Ergebnis. Eine Division machst du mit einer Multiplikation rückgängig und umgekehrt.",
      visual: "balance",
      steps: ["(□ · 6) : 8 = 27", "27 · 8 = 216", "216 : 6 = 36"],
      takeaway: "Vom Ergebnis aus: Reihenfolge umdrehen und Gegenoperation verwenden.",
    }],
  },
  "efficient-arithmetic": {
    id: "lesson-efficient-arithmetic-v1",
    topicId: "efficient-arithmetic",
    title: topics["efficient-arithmetic"].title,
    goal: "Du kannst eine gemeinsame Zahl ausklammern und dadurch mit runden Zahlen rechnen.",
    pages: [{
      eyebrow: "Struktur vor Rechnung",
      title: "Suche zuerst den gemeinsamen Faktor",
      body: "Zwei lange Multiplikationen sind oft gar nicht nötig. Kommt derselbe Faktor zweimal vor, kannst du ihn ausklammern und zuerst die einfachere Summe oder Differenz berechnen.",
      visual: "factor-pairs",
      steps: ["18 · 47 + 18 · 53", "18 · (47 + 53)", "18 · 100 = 1800"],
      takeaway: "Erst die Struktur vereinfachen, dann ausrechnen.",
    }],
  },
  "mass-units": {
    id: "lesson-mass-units-v1",
    topicId: "mass-units",
    title: topics["mass-units"].title,
    goal: "Du kannst Kilogramm und Gramm ohne Taschenrechner sicher ineinander umwandeln.",
    pages: [{
      eyebrow: "Grundidee",
      title: "Ein Kilogramm besteht aus 1000 Gramm",
      body: "Beim Wechsel von Kilogramm zu Gramm wird die Zahl 1000-mal so gross. In die andere Richtung wird sie 1000-mal kleiner.",
      visual: "mass-scale",
      steps: ["kg → g: mit 1000 multiplizieren", "g → kg: durch 1000 dividieren"],
      takeaway: "Die Einheit sagt dir, in welche Richtung du umrechnest.",
    }],
  },
  "fraction-of-quantity": {
    id: "lesson-fraction-quantity-v1",
    topicId: "fraction-of-quantity",
    title: topics["fraction-of-quantity"].title,
    goal: "Du kannst einen Bruchteil einer Menge bestimmen und deinen Rechenweg erklären.",
    pages: [{
      eyebrow: "Grundidee",
      title: "Zuerst teilen, dann nehmen",
      body: "Der Nenner sagt, in wie viele gleich grosse Teile du teilst. Der Zähler sagt, wie viele dieser Teile du brauchst.",
      visual: "fraction-forward",
      steps: ["48 : 4 = 12", "12 · 3 = 36", "Also sind 3/4 von 48 gleich 36."],
      takeaway: "Nenner: teilen. Zähler: multiplizieren.",
    }],
  },
  "time-fractions": {
    id: "lesson-time-fractions-v1",
    topicId: "time-fractions",
    title: topics["time-fractions"].title,
    goal: "Du kannst Bruchteile einer Zeitspanne berechnen, ohne Stunden und Minuten zu vermischen.",
    pages: [{
      eyebrow: "Eine Einheit",
      title: "Rechne zuerst alles in Minuten um",
      body: "Brüche lassen sich sicher berechnen, wenn die ganze Zeitspanne in derselben Einheit steht. Erst ganz am Schluss wandelst du bei Bedarf zurück.",
      visual: "clock-fraction",
      steps: ["2 h 20 min = 140 min", "1/7 davon: 140 : 7 = 20 min", "3/7 davon: 20 · 3 = 60 min"],
      takeaway: "Vor dem Bruchrechnen müssen alle Zeiten dieselbe Einheit haben.",
    }],
  },
  "speed-distance-time": {
    id: "lesson-speed-distance-time-v1",
    topicId: "speed-distance-time",
    title: topics["speed-distance-time"].title,
    goal: "Du kannst jede Bewegungsaufgabe auf Strecke, Zeit und Geschwindigkeit zurückführen.",
    pages: [{
      eyebrow: "Drei Grössen",
      title: "Der Durchschnitt braucht Gesamtstrecke und Gesamtzeit",
      body: "Geschwindigkeiten darfst du nicht einfach mitteln. Berechne für jeden Abschnitt seine Zeit, addiere alle Strecken und Zeiten und teile erst dann.",
      visual: "motion-model",
      steps: ["Zeit = Strecke : Geschwindigkeit", "Gesamtstrecke und Gesamtzeit addieren", "Durchschnitt = Gesamtstrecke : Gesamtzeit"],
      takeaway: "Der Durchschnitt ist Gesamtstrecke geteilt durch Gesamtzeit.",
    }],
  },
  "data-tables": {
    id: "lesson-data-tables-v1",
    topicId: "data-tables",
    title: topics["data-tables"].title,
    goal: "Du kannst in einer Tabelle die richtigen Zeilen und Spalten verbinden, ohne Werte zu vermischen.",
    pages: [{
      eyebrow: "Erst lesen, dann rechnen",
      title: "Markiere die Bedeutung jeder Zahl",
      body: "Eine Tabelle ordnet Informationen in Zeilen und Spalten. Lies zuerst die Überschriften, markiere dann nur die Zellen für deine Frage und schreibe auf, ob du ein Total, eine Differenz, einen Rest oder einen fehlenden Mittelwert suchst.",
      visual: "data-table",
      steps: ["gesuchte Zeile und Spalte markieren", "passende Werte mit Einheit notieren", "Rechenbeziehung festlegen", "Ergebnis mit der Tabelle kontrollieren"],
      takeaway: "Eine Zahl aus der falschen Zeile kann richtig gerechnet und trotzdem falsch sein.",
    }],
  },
  "money-calculations": {
    id: "lesson-money-calculations-v1",
    topicId: "money-calculations",
    title: topics["money-calculations"].title,
    goal: "Du kannst Preis, Anzahl und Einnahmen in beide Richtungen verbinden.",
    pages: [{
      eyebrow: "Drei Grössen",
      title: "Preis · Anzahl = Einnahmen",
      body: "Eine Zeile in einer Preistabelle enthält immer dieselbe Beziehung. Fehlt die Anzahl, teilst du die Einnahmen durch den Preis.",
      visual: "money-table",
      steps: ["Gruppenpreis: jede Anzahl mit ihrem Preis multiplizieren", "Besucherzahl: Einnahmen : Eintrittspreis"],
      takeaway: "Markiere zuerst, welche der drei Grössen gesucht ist.",
    }],
  },
  "proportional-revenue": {
    id: "lesson-proportional-revenue-v1",
    topicId: "proportional-revenue",
    title: topics["proportional-revenue"].title,
    goal: "Du kannst eine Einnahmetabelle lösen, wenn zwei Gruppen in einem festen Verhältnis stehen.",
    pages: [{
      eyebrow: "Bündeln",
      title: "Baue ein Paket aus dem Verhältnis",
      body: "Sind doppelt so viele Kinder wie Erwachsene da, gehören zwei Kindertickets und ein Erwachsenenticket in ein gemeinsames Paket.",
      visual: "money-table",
      steps: ["Bekannte Einnahmen vom Total abziehen", "Preis eines Verhältnis-Pakets berechnen", "Rest durch Paketpreis teilen", "Gesuchte Gruppenzahl aus den Paketen bestimmen"],
      takeaway: "Ein Verhältnis wird leichter, wenn du daraus ein wiederholbares Paket machst.",
    }],
  },
  "integer-combinations": {
    id: "lesson-integer-combinations-v1",
    topicId: "integer-combinations",
    title: topics["integer-combinations"].title,
    goal: "Du kannst beweisen, dass deine Liste aller Möglichkeiten vollständig ist.",
    pages: [{
      eyebrow: "Systematisch statt raten",
      title: "Halte eine Zahl fest und gehe geordnet weiter",
      body: "Beginne mit genau einer Münze der grössten Sorte. Erhöhe danach die mittlere Sorte Schritt für Schritt und berechne jeweils den Rest.",
      visual: "combination-grid",
      steps: ["Mindestens eine Münze jeder Sorte reservieren", "Grösste Sorte festhalten", "Mittlere Sorte in Einerschritten erhöhen", "Bei negativem Rest zur nächsten grossen Sorte wechseln"],
      takeaway: "Eine geordnete Tabelle verhindert Lücken und Doppelzählungen.",
    }],
  },
  "number-constraints": {
    id: "lesson-number-constraints-v1",
    topicId: "number-constraints",
    title: topics["number-constraints"].title,
    goal: "Du kannst alle Zahlen finden, die mehrere Bedingungen gleichzeitig erfüllen.",
    pages: [{
      eyebrow: "Filtern statt raten",
      title: "Nutze zuerst die stärkste Bedingung",
      body: "Beginne mit einer Teilbarkeitsregel oder einer festen Endziffer. Verteile erst danach die erlaubten Ziffern – mit oder ohne Wiederholung, genau wie verlangt – und prüfe die Stellenbedingung. So bleibt deine Liste überschaubar und vollständig.",
      visual: "number-filter",
      steps: ["Teilbarkeit auf mögliche Enden anwenden", "übrige Ziffern geordnet verteilen", "Stellenbedingung prüfen", "Doppelungen streichen und Vollständigkeit kontrollieren"],
      takeaway: "Jede Bedingung ist ein Filter; am Ende müssen alle gleichzeitig gelten.",
    }],
  },
  "area-fractions": {
    id: "lesson-area-fractions-v1",
    topicId: "area-fractions",
    title: topics["area-fractions"].title,
    goal: "Du kannst verschieden grosse Platten als gleich grosse Flächeneinheiten zählen.",
    pages: [{
      eyebrow: "Gleiche Einheiten",
      title: "Zähle Fläche, nicht nur Platten",
      body: "Eine grosse 2×2-Platte bedeckt dieselbe Fläche wie vier kleine Platten. Erst wenn alles in kleinen Einheitsquadraten gezählt ist, bildest und kürzt du den Bruch.",
      visual: "tile-grid",
      steps: ["Gesamtfläche in Einheitsquadraten zählen", "Grosse Platten als vier Einheiten abziehen", "weisse Fläche / Gesamtfläche bilden", "Bruch vollständig kürzen"],
      takeaway: "Bei Flächenanteilen müssen Zähler und Nenner dieselbe Flächeneinheit verwenden.",
    }],
  },
  "composite-areas": {
    id: "lesson-composite-areas-v1",
    topicId: "composite-areas",
    title: topics["composite-areas"].title,
    goal: "Du kannst eine zusammengesetzte Figur in bekannte Rechtecke zerlegen.",
    pages: [{
      eyebrow: "Ergänzen oder abziehen",
      title: "Starte mit einem einfachen Aussenrechteck",
      body: "Rahmen und L-Formen werden leichter, wenn du zuerst das ganze umschliessende Rechteck berechnest. Ziehe danach Ausschnitte ab. Beim Umfang verfolgst du stattdessen jede Randstrecke.",
      visual: "area-cutout",
      steps: ["Aussenrechteck erkennen", "fehlende Innenmasse bestimmen", "Teilflächen addieren oder Ausschnitt abziehen", "bei Umfang alle Randstrecken einmal zählen"],
      takeaway: "Fläche misst das Innere; Umfang verfolgt den Rand.",
    }],
  },
  "tiling-costs": {
    id: "lesson-tiling-costs-v1",
    topicId: "tiling-costs",
    title: topics["tiling-costs"].title,
    goal: "Du kannst die günstigste Mischung aus kleinen und grossen Platten bestimmen.",
    pages: [{
      eyebrow: "Optimieren",
      title: "Vergleiche zuerst den Preis pro Fläche",
      body: "Eine grosse Platte bedeckt vier Einheitsquadrate. Ist sie günstiger als vier kleine, verwendest du so viele grosse Platten wie geometrisch hineinpassen.",
      visual: "tile-grid",
      steps: ["Kosten einer grossen Platte mit vier kleinen vergleichen", "Anzahl passender 2×2-Platten bestimmen", "Restflächen mit kleinen Platten füllen", "beide Kosten addieren"],
      takeaway: "Billiger pro Fläche genügt nicht: Die grossen Platten müssen auch ins Rechteck passen.",
    }],
  },
  "reverse-fractions": {
    id: "lesson-reverse-fractions-v1",
    topicId: "reverse-fractions",
    title: topics["reverse-fractions"].title,
    goal: "Du kannst aus einem bekannten Bruchteil die ursprüngliche Gesamtmenge finden.",
    pages: [
      {
        eyebrow: "Neue Idee",
        title: "Rückwärts heisst: erst einen Teil finden",
        body: "Wenn 3/4 einer Masse 18 kg sind, kennst du drei gleich grosse Teile. Finde zuerst einen Teil und danach alle vier Teile.",
        visual: "fraction-backward",
        steps: ["3 Teile sind 18 kg.", "1 Teil ist 18 : 3 = 6 kg.", "4 Teile sind 6 · 4 = 24 kg."],
        takeaway: "Durch den Zähler teilen, mit dem Nenner multiplizieren.",
      },
      {
        eyebrow: "Kontrolle",
        title: "Prüfe die Richtung",
        body: "Die ursprüngliche Menge muss grösser sein als der übrig gebliebene Anteil. Ist dein Resultat kleiner, bist du wahrscheinlich vorwärts statt rückwärts gegangen.",
        visual: "fraction-backward",
        steps: ["3/4 von 24 kg = 18 kg", "18 kg < 24 kg — die Richtung stimmt."],
        takeaway: "Eine kurze Grössenprüfung entdeckt viele Fehler.",
      },
    ],
  },
  "reverse-chains": {
    id: "lesson-reverse-chains-v1",
    topicId: "reverse-chains",
    title: topics["reverse-chains"].title,
    goal: "Du kannst eine Sachaufgabe vom Endergebnis Schritt für Schritt rückwärts lösen.",
    pages: [{
      eyebrow: "Strategie",
      title: "Beginne dort, wo du eine sichere Zahl kennst",
      body: "Bei Rückwärtsaufgaben steht die sicherste Zahl oft am Ende: zum Beispiel die Anzahl gefüllter Gläser. Rechne jede Veränderung in umgekehrter Reihenfolge zurück.",
      visual: "reverse-chain",
      steps: ["Inhalt aller Gläser bestimmen.", "Den Verlust beim Einkochen rückgängig machen.", "Aussortierte Ware zurückrechnen.", "Den Verlust beim Transport addieren."],
      takeaway: "Schreibe jeden rückwärts gelösten Schritt in eine eigene Zeile.",
    }],
  },
  "inverse-proportion": {
    id: "lesson-inverse-proportion-v1",
    topicId: "inverse-proportion",
    title: topics["inverse-proportion"].title,
    goal: "Du kannst eine konstante Gesamtmenge wie Personentage erkennen und verwenden.",
    pages: [{
      eyebrow: "Invariante",
      title: "Personen · Tage bleibt gleich",
      body: "Wenn dieselbe Vorratsmenge auf weniger Personen verteilt wird, reicht sie länger. Das Produkt aus Personen und Tagen beschreibt den gesamten Vorrat.",
      visual: "supply-model",
      steps: ["40 Personen · 24 Tage = 960 Personentage", "960 : 30 Personen = 32 Tage", "Gesuchte Verlängerung: 32 − 24 = 8 Tage"],
      takeaway: "Wird eine Grösse kleiner, wird die andere im gleichen Verhältnis grösser.",
    }],
  },
  "changing-rates": {
    id: "lesson-changing-rates-v1",
    topicId: "changing-rates",
    title: topics["changing-rates"].title,
    goal: "Du kannst einen Vorrat über mehrere Verbrauchsphasen verfolgen.",
    pages: [{
      eyebrow: "Zwei Phasen",
      title: "Ziehe zuerst den bereits verbrauchten Vorrat ab",
      body: "Ändert sich die Personenzahl, darfst du nicht mit der ursprünglichen Dauer weiterrechnen. Halte den Vorrat in Personentagen fest.",
      visual: "supply-model",
      steps: ["Gesamte Personentage bestimmen", "Verbrauch der ersten Phase abziehen", "Rest durch die neue Personenzahl teilen"],
      takeaway: "An jedem Wechselpunkt brauchst du eine neue Rechnung mit dem verbleibenden Vorrat.",
    }],
  },
  "geometric-loci": {
    id: "lesson-geometric-loci-v1",
    topicId: "geometric-loci",
    title: topics["geometric-loci"].title,
    goal: "Du kannst sprachliche Abstandsbedingungen in geometrische Grenzen übersetzen.",
    pages: [{
      eyebrow: "Bedingung → Grenze",
      title: "Jede Aussage zeichnet eine geometrische Spur",
      body: "Gleicher Abstand zu zwei Punkten ergibt eine Mittelsenkrechte. Ein fester Abstand von einem Punkt ergibt einen Kreis; von einer Geraden eine Parallele.",
      visual: "locus-map",
      steps: ["Massstab in die Zeichnungseinheit umrechnen", "für jede Bedingung die passende Grenze konstruieren", "richtige Seite oder Innen-/Aussenbereich markieren", "alle Bedingungen schneiden"],
      takeaway: "Das Lösungsgebiet ist die Schnittmenge aller erlaubten Bereiche.",
    }],
  },
  "coordinate-transformations": {
    id: "lesson-coordinate-transformations-v1",
    topicId: "coordinate-transformations",
    title: topics["coordinate-transformations"].title,
    goal: "Du kannst einen Punkt mit einer Koordinatenregel spiegeln, drehen oder verschieben.",
    pages: [{
      eyebrow: "Koordinaten statt Raten",
      title: "Verändere x und y nach einer festen Regel",
      body: "Bei einer Abbildung wird nicht frei gezeichnet. Spiegelachsen, Drehungen und Verschiebungsvektoren geben genau vor, welche Koordinate bleibt, ihr Vorzeichen wechselt oder ihren Platz tauscht.",
      visual: "coordinate-plane",
      steps: ["Ausgangspunkt (x | y) notieren", "Abbildungsregel auf beide Koordinaten anwenden", "Bildpunkt (x′ | y′) eintragen", "Lage im Quadranten kontrollieren"],
      takeaway: "Erst die Regel symbolisch schreiben, dann die Zahlen einsetzen.",
    }],
  },
  "cube-nets": {
    id: "lesson-cube-nets-v1",
    topicId: "cube-nets",
    title: topics["cube-nets"].title,
    goal: "Du kannst ein Würfelnetz Fläche für Fläche falten und Gegenflächen sicher erkennen.",
    pages: [{
      eyebrow: "Vom Netz zum Körper",
      title: "Klappe immer nur über eine Kante",
      body: "Wähle eine Fläche als Boden. Direkt angrenzende Flächen klappen zu Seiten hoch. Eine weitere Fläche kann dann zum Deckel werden. Verfolge nach jedem Klappen, in welche Raumrichtung die Fläche zeigt.",
      visual: "cube-net",
      steps: ["eine Startfläche festhalten", "direkte Nachbarn als Seiten hochklappen", "weitere Flächen Kante für Kante verfolgen", "entgegengesetzte Raumrichtungen als Gegenflächen markieren"],
      takeaway: "Direkt benachbarte Netzfelder sind nie Gegenflächen des Würfels.",
    }],
  },
  "spatial-rolling": {
    id: "lesson-spatial-rolling-v1",
    topicId: "spatial-rolling",
    title: topics["spatial-rolling"].title,
    goal: "Du kannst beim Kippen einer dreiseitigen Pyramide jede Fläche verfolgen.",
    pages: [{
      eyebrow: "Kantenrolle",
      title: "Die Fläche hinter der Kippkante wird zur Grundfläche",
      body: "Benenne vor jedem Kippen Grundfläche, linke, rechte und hintere Fläche. Zeichne die neue Grundfläche in das Zielfeld, bevor du weiterkippst.",
      visual: "pyramid-roll",
      steps: ["Kippkante markieren", "angrenzende Seitenfläche wird unten", "alte Grundfläche kommt an die Kippkante", "die beiden übrigen Seiten tauschen", "neue Lage vollständig beschriften"],
      takeaway: "Verfolge nicht die ganze Figur auf einmal – aktualisiere nach jeder einzelnen Kante.",
    }],
  },
  "cuboid-surface": {
    id: "lesson-cuboid-surface-v1",
    topicId: "cuboid-surface",
    title: topics["cuboid-surface"].title,
    goal: "Du kannst unbekannte Bausteinmasse aus Volumen und Anordnungen erschliessen.",
    pages: [{
      eyebrow: "Vom Volumen zur Oberfläche",
      title: "Bestimme zuerst Länge, Breite und Höhe",
      body: "Zwei gleiche Bausteine können je nach Anordnung eine bekannte Gesamtlänge verraten. Danach liefert Volumen = Länge · Breite · Höhe die fehlende Kante.",
      visual: "cuboid-net",
      steps: ["Gesamtmass durch zwei teilen, falls zwei gleiche Kanten aneinanderliegen", "Volumen eines Bausteins bestimmen", "fehlende Höhe berechnen", "Oberfläche: 2 · (L·B + L·H + B·H)"],
      takeaway: "Eine Oberfläche besteht aus drei verschiedenen Rechtecken – jedes kommt zweimal vor.",
    }],
  },
}

export function orderedTopics(): TopicDefinition[] {
  return Object.values(topics).sort((left, right) => left.courseOrder - right.courseOrder)
}
