import type { TopicId } from "./model"
import type { TopicCoachingContent } from "./parentCoaching"

export const spanishTopicCoaching = {
  "arithmetic-equations": {
    title: "Encontrar números desconocidos trabajando hacia atrás",
    description: "Deshaz multiplicaciones y divisiones en orden inverso.",
    goal: "Puedes resolver una cadena de cálculo hacia atrás a partir del resultado conocido.",
    ideaTitle: "Deshaz cada operación",
    idea: "Empieza por el resultado. Invierte el orden de las operaciones y sustituye cada una por su operación inversa: multiplicar se convierte en dividir y dividir en multiplicar.",
    commonHurdle: "Las operaciones se deshacen en su orden original en vez de empezar por la última.",
    nextStep: "Escribe la cadena como flechas, empieza por el resultado e invierte una flecha cada vez.",
    workedSteps: ["(□ × 6) ÷ 8 = 27", "27 × 8 = 216", "216 ÷ 6 = 36"],
    takeaway: "Empieza por el resultado: invierte el orden y usa las operaciones inversas.",
  },
  "efficient-arithmetic": {
    title: "Reconocer y usar estructuras de cálculo eficientes",
    description: "Detecta factores comunes y sumas o diferencias redondas antes de calcular.",
    goal: "Puedes sacar un factor común y calcular con un total redondo.",
    ideaTitle: "Busca primero el factor común",
    idea: "Dos multiplicaciones largas pueden ocultar un cálculo corto. Cuando el mismo factor aparece dos veces, sácalo como factor común y combina primero los números restantes.",
    commonHurdle: "Se calculan los dos productos por separado y se pierde la estructura común útil.",
    nextStep: "Rodea el factor repetido y coloca entre paréntesis los otros dos números.",
    workedSteps: ["18 × 47 + 18 × 53", "18 × (47 + 53)", "18 × 100 = 1800"],
    takeaway: "Simplifica la estructura antes de hacer las operaciones.",
  },
  "mass-units": {
    title: "Convertir kilogramos y gramos con seguridad",
    description: "Convierte masas entre kilogramos y gramos.",
    goal: "Puedes convertir kilogramos y gramos con precisión y sin calculadora.",
    ideaTitle: "Un kilogramo son 1000 gramos",
    idea: "El número se hace 1000 veces mayor al pasar de kilogramos a gramos y 1000 veces menor al pasar de gramos a kilogramos.",
    commonHurdle: "Se conoce el factor correcto, pero se multiplica o divide en la dirección equivocada.",
    nextStep: "Di en voz alta la unidad de destino y estima si el número debe aumentar o disminuir.",
    workedSteps: ["kg → g: multiplicar por 1000", "g → kg: dividir entre 1000"],
    takeaway: "La unidad de destino indica en qué dirección debes convertir.",
  },
  "fraction-of-quantity": {
    title: "Calcular una fracción de una cantidad",
    description: "Calcula una fracción, como 3/4, de una cantidad dada.",
    goal: "Puedes calcular una fracción de una cantidad y explicar el procedimiento.",
    ideaTitle: "Primero divide y después toma las partes necesarias",
    idea: "El denominador indica cuántas partes iguales forman el total. El numerador indica cuántas de esas partes necesitas.",
    commonHurdle: "Se intercambian numerador y denominador o se intentan hacer ambas operaciones a la vez.",
    nextStep: "Halla una parte usando el denominador y después multiplícala por el numerador.",
    workedSteps: ["48 ÷ 4 = 12", "12 × 3 = 36", "Por tanto, 3/4 de 48 es 36."],
    takeaway: "Denominador: divide. Numerador: multiplica.",
  },
  "time-fractions": {
    title: "Calcular fracciones de intervalos de tiempo",
    description: "Expresa horas y minutos en una sola unidad antes de calcular una fracción.",
    goal: "Puedes calcular fracciones de tiempo sin mezclar horas y minutos.",
    ideaTitle: "Convierte primero todo a minutos",
    idea: "El cálculo con fracciones es fiable solo si todo el intervalo usa la misma unidad. Vuelve a convertir a horas únicamente después de hallar la fracción.",
    commonHurdle: "Se tratan horas y minutos como si fueran partes decimales del mismo número.",
    nextStep: "Escribe la duración completa en minutos en una línea aparte antes de usar la fracción.",
    workedSteps: ["2 h 20 min = 140 min", "1/7: 140 ÷ 7 = 20 min", "3/7: 20 × 3 = 60 min"],
    takeaway: "Todos los tiempos deben tener la misma unidad antes de aplicar una fracción.",
  },
  "speed-distance-time": {
    title: "Relacionar distancia, tiempo y velocidad",
    description: "Calcula velocidades medias y distancias de alcance a lo largo de varios periodos.",
    goal: "Puedes reducir un problema de movimiento a distancia, tiempo y velocidad.",
    ideaTitle: "Una media necesita la distancia y el tiempo totales",
    idea: "Normalmente no se pueden promediar velocidades de forma directa. Calcula el tiempo de cada tramo, suma todas las distancias y tiempos y divide solo al final.",
    commonHurdle: "Se promedian dos velocidades aunque sus tiempos o distancias sean diferentes.",
    nextStep: "Crea una fila para cada tramo con distancia, tiempo y velocidad; después suma las dos primeras columnas.",
    workedSteps: ["Tiempo = distancia ÷ velocidad", "Suma la distancia total y el tiempo total", "Velocidad media = distancia total ÷ tiempo total"],
    takeaway: "La velocidad media es la distancia total dividida entre el tiempo total.",
  },
  "data-tables": {
    title: "Relacionar correctamente los datos de una tabla",
    description: "Lee filas y columnas con atención y reconstruye valores o medias que faltan.",
    goal: "Puedes relacionar la fila y la columna correctas sin mezclar valores ajenos.",
    ideaTitle: "Nombra cada número antes de calcular",
    idea: "Una tabla da significado mediante los encabezados de filas y columnas. Selecciona solo las celdas necesarias y decide si buscas un total, una diferencia, un resto o una media desconocida.",
    commonHurdle: "Un cálculo matemáticamente correcto usa un valor de la fila o columna equivocada.",
    nextStep: "Sigue el encabezado de la fila y de la columna hasta cada celda elegida antes de escribir la ecuación.",
    workedSteps: ["Marca la fila y la columna necesarias", "Escribe los valores relevantes con sus unidades", "Elige la relación", "Contrasta el resultado con la tabla"],
    takeaway: "Una operación correcta con la celda equivocada también da una respuesta incorrecta.",
  },
  "money-calculations": {
    title: "Relacionar precios, cantidades e ingresos",
    description: "Halla precios de grupos o cantidades a partir de precios e ingresos.",
    goal: "Puedes pasar en ambas direcciones entre precio, cantidad e ingresos.",
    ideaTitle: "Precio × cantidad = ingresos",
    idea: "Cada fila de una tabla de precios usa la misma relación. Si falta la cantidad, divide los ingresos entre el precio.",
    commonHurdle: "Se multiplica cuando la cantidad desconocida exige dividir o se omite la unidad monetaria.",
    nextStep: "Nombra primero la incógnita y después tápala en la relación precio × cantidad = ingresos.",
    workedSteps: ["Ingresos del grupo: multiplica cada cantidad por su precio", "Cantidad: ingresos ÷ precio unitario"],
    takeaway: "Primero identifica cuál de las tres magnitudes falta.",
  },
  "proportional-revenue": {
    title: "Resolver proporciones en tablas de ingresos",
    description: "Resta los ingresos conocidos y agrupa categorías en una proporción fija.",
    goal: "Puedes resolver una tabla de ingresos cuando dos grupos aparecen en una proporción fija.",
    ideaTitle: "Convierte la proporción en un paquete repetible",
    idea: "Si hay el doble de niños que de adultos, un paquete contiene dos entradas infantiles y una de adulto. Los ingresos restantes se forman con paquetes completos.",
    commonHurdle: "La proporción se trata como una diferencia y no como grupos que se repiten juntos.",
    nextStep: "Dibuja un paquete completo de la proporción y calcula su precio combinado antes de dividir los ingresos restantes.",
    workedSteps: ["Resta del total los ingresos conocidos", "Calcula el precio de un paquete proporcional", "Divide el resto entre el precio del paquete", "Recupera la cantidad del grupo buscado"],
    takeaway: "Una proporción es más sencilla cuando se convierte en un paquete repetible.",
  },
  "integer-combinations": {
    title: "Encontrar sistemáticamente todas las combinaciones enteras",
    description: "Enumera todas las combinaciones sin huecos ni casos duplicados.",
    goal: "Puedes justificar que una lista de combinaciones enteras está completa.",
    ideaTitle: "Fija un valor y cambia el siguiente en orden",
    idea: "Empieza con una cantidad fija del objeto mayor. Aumenta la cantidad intermedia de uno en uno y calcula cada vez la cantidad restante.",
    commonHurdle: "Se adivinan combinaciones plausibles, dejando huecos o contando dos veces el mismo caso.",
    nextStep: "Usa una tabla ordenada y cambia solo una columna cada vez hasta que el resto sea negativo.",
    workedSteps: ["Reserva al menos un objeto de cada tipo", "Fija el tipo mayor", "Aumenta el tipo intermedio de uno en uno", "Pasa a la siguiente cantidad mayor cuando el resto sea negativo"],
    takeaway: "Una tabla ordenada evita huecos y recuentos dobles.",
  },
  "number-constraints": {
    title: "Encontrar todos los números que cumplen varias condiciones",
    description: "Combina cifras, divisibilidad y valor posicional en un conjunto completo de soluciones.",
    goal: "Puedes encontrar cada número que cumple varias condiciones a la vez.",
    ideaTitle: "Usa primero el filtro más fuerte",
    idea: "Empieza por una regla de divisibilidad o una terminación fija. Ordena después las cifras restantes y comprueba al final la condición de valor posicional.",
    commonHurdle: "Se comprueban los candidatos con una condición, pero no con todas, o se omiten ordenaciones válidas.",
    nextStep: "Crea una columna de filtro para cada condición y conserva un candidato solo si supera todas.",
    workedSteps: ["Aplica la divisibilidad a las posibles terminaciones", "Ordena sistemáticamente las cifras restantes", "Comprueba la condición de valor posicional", "Elimina duplicados y demuestra que la lista está completa"],
    takeaway: "Cada condición es un filtro; toda respuesta final debe superarlos todos.",
  },
  "area-fractions": {
    title: "Contar y simplificar fracciones de área",
    description: "Convierte baldosas de tamaños diferentes en unidades de área iguales.",
    goal: "Puedes contar baldosas diferentes usando una unidad de área común.",
    ideaTitle: "Cuenta el área, no el número de baldosas",
    idea: "Una baldosa de 2×2 cubre la misma área que cuatro baldosas unidad. Convierte todo a cuadrados unidad antes de formar y simplificar la fracción.",
    commonHurdle: "Las baldosas grandes y pequeñas se cuentan como un objeto cada una aunque cubran áreas distintas.",
    nextStep: "Dibuja o cuenta los cuadrados unidad que hay bajo cada baldosa antes de escribir numerador y denominador.",
    workedSteps: ["Cuenta el área total en cuadrados unidad", "Convierte cada baldosa grande en cuatro unidades", "Forma área blanca ÷ área total", "Simplifica por completo"],
    takeaway: "El numerador y el denominador deben usar la misma unidad de área.",
  },
  "composite-areas": {
    title: "Descomponer áreas compuestas",
    description: "Calcula marcos, recortes y muescas sumando o restando rectángulos.",
    goal: "Puedes dividir una figura compuesta en rectángulos conocidos.",
    ideaTitle: "Empieza por un rectángulo exterior sencillo",
    idea: "Los marcos y las figuras en L suelen simplificarse calculando el rectángulo que los envuelve y restando los recortes. Para el perímetro, sigue en cambio cada borde exterior.",
    commonHurdle: "Se mezclan los métodos de área y perímetro o se cuenta un borde interior como parte del contorno exterior.",
    nextStep: "Marca la tarea como ÁREA o PERÍMETRO y después sombrea las piezas interiores o recorre solo el contorno exterior.",
    workedSteps: ["Identifica el rectángulo exterior", "Halla las longitudes interiores que faltan", "Suma piezas o resta el recorte", "Para el perímetro, cuenta cada tramo del contorno una vez"],
    takeaway: "El área mide el interior; el perímetro sigue el contorno.",
  },
  "tiling-costs": {
    title: "Cubrir un área al coste mínimo",
    description: "Ten en cuenta a la vez el encaje geométrico y el coste por área.",
    goal: "Puedes encontrar la mezcla válida más barata de baldosas pequeñas y grandes.",
    ideaTitle: "Compara primero el coste por área cubierta",
    idea: "Una baldosa grande cubre cuatro cuadrados unidad. Si cuesta menos que cuatro baldosas pequeñas, usa tantas grandes como realmente quepan en el rectángulo.",
    commonHurdle: "Se elige el precio por área más barato sin comprobar si las baldosas grandes caben en las dimensiones.",
    nextStep: "Compara precios, dibuja la colocación máxima válida de 2×2 y cuenta los cuadrados unidad que quedan.",
    workedSteps: ["Compara una baldosa grande con cuatro pequeñas", "Halla cuántas baldosas de 2×2 caben", "Rellena el área restante con baldosas pequeñas", "Suma ambos costes"],
    takeaway: "Ser más barato por área solo sirve si las baldosas grandes también caben.",
  },
  "reverse-fractions": {
    title: "Trabajar hacia atrás desde una fracción conocida",
    description: "Recupera el total original a partir de una parte fraccionaria conocida.",
    goal: "Puedes hallar una cantidad original a partir de una fracción conocida de ella.",
    ideaTitle: "Halla primero una parte igual",
    idea: "Si 3/4 de una masa son 18 kg, esos 18 kg representan tres partes iguales. Divide para hallar una parte y multiplica después para reconstruir las cuatro.",
    commonHurdle: "Se repite el método directo de fracciones y se obtiene un resultado menor que la parte conocida.",
    nextStep: "Indica cuántas partes iguales representa la cantidad conocida, halla una y reconstruye después el total.",
    workedSteps: ["3 partes son 18 kg", "1 parte es 18 ÷ 3 = 6 kg", "4 partes son 6 × 4 = 24 kg", "Comprobación: 3/4 de 24 kg son 18 kg"],
    takeaway: "Divide entre el numerador y multiplica después por el denominador.",
  },
  "reverse-chains": {
    title: "Resolver procesos de varios pasos hacia atrás",
    description: "Deshaz varios cambios en el orden inverso correcto.",
    goal: "Puedes resolver un problema escrito hacia atrás a partir de la cantidad final conocida.",
    ideaTitle: "Empieza donde el valor es seguro",
    idea: "El valor más fiable suele estar al final de la historia. Deshaz cada cambio en orden inverso y escribe una operación en cada línea.",
    commonHurdle: "Se usan las operaciones inversas correctas, pero en el mismo orden que la historia y no en orden inverso.",
    nextStep: "Escribe la historia como una cadena de flechas hacia delante y recórrela después hacia atrás, flecha a flecha.",
    workedSteps: ["Halla el contenido total de todos los recipientes", "Deshaz la pérdida del proceso", "Restaura el material rechazado", "Añade de nuevo la pérdida del transporte"],
    takeaway: "Escribe cada paso hacia atrás en una línea propia.",
  },
  "inverse-proportion": {
    title: "Comprender la proporcionalidad inversa",
    description: "Reconoce cuándo menos personas pueden usar el mismo recurso durante más tiempo.",
    goal: "Puedes identificar y usar un total constante, como personas-día.",
    ideaTitle: "Personas × días se mantiene constante",
    idea: "Cuando menos personas comparten el mismo recurso, este dura más. Las personas-día representan todo el recurso fijo.",
    commonHurdle: "El número de días cambia en la misma dirección que el de personas, como si la relación fuera directa.",
    nextStep: "Calcula primero el total fijo de personas-día y divídelo entre el nuevo número de personas.",
    workedSteps: ["40 personas × 24 días = 960 personas-día", "960 ÷ 30 personas = 32 días", "Prolongación: 32 − 24 = 8 días"],
    takeaway: "Cuando una cantidad disminuye, la otra aumenta en la proporción correspondiente.",
  },
  "changing-rates": {
    title: "Calcular el consumo en fases cambiantes",
    description: "Halla el recurso restante antes de calcular una duración nueva.",
    goal: "Puedes seguir un recurso fijo a través de varias fases de consumo.",
    ideaTitle: "Resta lo que ya se ha consumido",
    idea: "Cuando cambia el número de personas, la duración original deja de ser válida. Mantén el recurso en personas-día, resta la primera fase y calcula después la segunda.",
    commonHurdle: "El grupo nuevo se aplica al recurso inicial completo y no a lo que queda.",
    nextStep: "Dibuja un límite claro entre fases y escribe las personas-día totales, usadas y restantes antes de la división final.",
    workedSteps: ["Calcula el total de personas-día", "Resta el consumo de la primera fase", "Divide el resto entre el nuevo número de personas"],
    takeaway: "En cada cambio, vuelve a calcular a partir del recurso restante.",
  },
  "geometric-loci": {
    title: "Construir regiones a partir de condiciones geométricas",
    description: "Interpreta distancias, círculos y mediatrices como fronteras de una región.",
    goal: "Puedes traducir condiciones verbales de distancia en fronteras geométricas.",
    ideaTitle: "Cada condición crea una frontera geométrica",
    idea: "La misma distancia a dos puntos produce una mediatriz. Una distancia fija a un punto produce un círculo; una distancia fija a una recta produce una paralela.",
    commonHurdle: "Se dibuja la frontera correcta, pero se elige el lado, la escala o la región de intersección equivocados.",
    nextStep: "Para cada condición, nombra la frontera y prueba un punto para decidir qué lado está permitido.",
    workedSteps: ["Convierte la escala a unidades del dibujo", "Construye una frontera por condición", "Marca el lado permitido o la región interior/exterior", "Interseca todas las regiones permitidas"],
    takeaway: "La solución es la intersección de todas las regiones permitidas.",
  },
  "coordinate-transformations": {
    title: "Reflejar, girar y trasladar puntos",
    description: "Aplica reglas de coordenadas para simetrías, cuartos de vuelta y traslaciones.",
    goal: "Puedes transformar un punto mediante una regla precisa de coordenadas.",
    ideaTitle: "Cambia x e y según una regla fija",
    idea: "Una transformación no es un dibujo a mano alzada. Su eje, ángulo o vector determina qué coordenada se mantiene, cambia de signo, intercambia su posición o recibe un desplazamiento.",
    commonHurdle: "Se cambian automáticamente los dos signos o se intercambian x e y cuando la transformación no lo exige.",
    nextStep: "Escribe primero la regla simbólica, aplícala por separado a x e y y comprueba el cuadrante resultante.",
    workedSteps: ["Escribe el punto inicial (x, y)", "Aplica la regla a ambas coordenadas", "Dibuja el punto imagen (x′, y′)", "Comprueba su cuadrante y distancia"],
    takeaway: "Escribe la regla simbólica antes de sustituir los números.",
  },
  "cube-nets": {
    title: "Plegar mentalmente desarrollos de cubos",
    description: "Determina las caras vecinas y opuestas plegando un desarrollo en el espacio.",
    goal: "Puedes plegar un desarrollo cara a cara e identificar con seguridad las caras opuestas.",
    ideaTitle: "Pliega un borde cada vez",
    idea: "Elige una cara como base. Las vecinas directas se levantan como lados; otra cara puede convertirse después en la superior. Sigue la dirección espacial tras cada pliegue.",
    commonHurdle: "Dos caras que se tocan en el desarrollo plano se identifican por error como opuestas.",
    nextStep: "Fija una cara base y asigna a cada vecina plegada una dirección: delante, detrás, izquierda, derecha o arriba.",
    workedSteps: ["Fija una cara inicial", "Levanta las vecinas directas como lados", "Continúa un borde cada vez", "Empareja las caras que apuntan en direcciones opuestas"],
    takeaway: "Dos caras que comparten un borde en el desarrollo nunca pueden ser opuestas en el cubo.",
  },
  "spatial-rolling": {
    title: "Seguir una pirámide mientras rueda",
    description: "Sigue con seguridad cada cara mientras el sólido vuelca sobre sus aristas.",
    goal: "Puedes seguir cada cara de una pirámide triangular durante una secuencia de vuelcos.",
    ideaTitle: "La cara que está al otro lado de la arista se convierte en la base",
    idea: "Antes de cada vuelco, nombra la base y las tres caras laterales. Actualiza toda la orientación tras una arista antes de intentar el siguiente vuelco.",
    commonHurdle: "Se imaginan varios vuelcos a la vez y se pierde la orientación de un paso anterior.",
    nextStep: "Usa una tabla de cuatro posiciones y vuelve a escribir base, izquierda, derecha y atrás después de cada vuelco.",
    workedSteps: ["Marca la arista de vuelco", "Mueve la cara lateral adyacente a la base", "Mueve la base anterior al lado del vuelco", "Actualiza las caras restantes", "Etiqueta la nueva orientación completa"],
    takeaway: "No sigas todo el recorrido a la vez: actualiza después de cada arista.",
  },
  "cuboid-surface": {
    title: "Recuperar las dimensiones y el área total de un ortoedro",
    description: "Deduce las dimensiones de los bloques y calcula las seis caras de un ortoedro.",
    goal: "Puedes recuperar dimensiones desconocidas de bloques a partir del volumen y su disposición.",
    ideaTitle: "Halla primero largo, ancho y alto",
    idea: "Una disposición de bloques iguales puede revelar una dimensión. Después, volumen = largo × ancho × alto permite hallar la arista que falta antes de calcular el área total.",
    commonHurdle: "Se mezclan las fórmulas del volumen y del área total o se cuenta una pareja de caras solo una vez.",
    nextStep: "Anota las tres longitudes con unidades, enumera los tres rectángulos de cara diferentes y duplica cada uno.",
    workedSteps: ["Divide una longitud combinada cuando se tocan dos aristas iguales", "Halla el volumen de un bloque", "Calcula la altura que falta", "Área total = 2 × (L×A + L×H + A×H)"],
    takeaway: "Un ortoedro tiene tres rectángulos de cara diferentes y cada uno aparece dos veces.",
  },
} satisfies Record<TopicId, TopicCoachingContent>
